module.exports={
  "user":[
    {
      "userPhoto":"./img/1.jpg",
      "username":"baby",
      "contentTitle":"我是一个自由的小小鸟一直飞也飞不高",
      "content":"./img/b.jpg"
    },
    {
      "userPhoto":"./img/a.jpg",
      "username":"baby2",
      "contentTitle":"我是一个自由的小小鸟一直飞也飞不高",
      "content":"./img/3.jpg"
    }
  ]
};